import { Plus_Jakarta_Sans, Jersey_25 } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const font = Plus_Jakarta_Sans({ subsets: ["latin"] });
const jersey = Jersey_25({
  subsets: ["latin"],
  variable: "--font-jersey",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${font.className} ${jersey.variable} text-white bg-[#161513]`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
